version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: trading-redis
    ports:
      - "6379:6379"
    networks:
      - trading-network
  grafana:
    image: grafana/grafana:latest
    container_name: trading-grafana
    ports:
      - "3000:3000"
    networks:
      - trading-network
networks:
  trading-network:
    driver: bridge
